# Language and versions:
language: python
python:
  - "3.7"
  - "3.8"

# Command to install dependencies:
before_install:
  - pip install -r requirements.txt
  - export PYTHONPATH=$PYTHONPATH:$(pwd)
  - python setup.py install

# Command to run pytests:
script: pytest
